baseurl = "https://bettercli.org/"
title = "BetterCLI.org"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10

[outputs]
  home = ["HTML", "RSS"]

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categories"

[permalinks]
  blog = "/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  includeNewer = true
  threshold = 0
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
